name: David Molina
title: David Molina.
description: "David Molina writes on institutional strategy and hemispheric governance, with a focus on North American resilience."
author: David Molina
repository: davidmolina/davidmolina.github.io
email: david.c.molina@gmail.com

# RDF structured data
job_title: Advisor
employer: Strategist.
url: "https://davidmolina.github.io/"
location:
  city: Portland
  state: Oregon
  country: United States of America

# Social metadata
social:
  name: David Molina
  links:
    - https://facebook.com/david.molina1
    - https://instagram.com/davidcmolina
    - https://github.com/davidmolina

navigation:
  - title: About
    url: /about
  - title: Now
    url: /now
  - title: Press
    url: /press
  - title: Connecting
    url: /connecting
  - title: Events
    url: /events
  - title: Resume
    url: /resume

# Misc
twitter_username: davidcmolina
github_username:  davidmolina
facebook_username: david.molina1
instagram_username: davidcmolina

# Build settings
markdown: kramdown
branch: master

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Permalink structure, see http://jekyllrb.com/docs/permalinks/
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
